[package]
name = "executables_installer"
version = "0.1.2"
edition = "2024"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
lib_cli.workspace = true
anyhow.workspace = true
