name: Rust

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check formatting
        run: cargo fmt --check
      - name: Linter
        run: cargo clippy -- -Dwarnings

  build:
    runs-on: ubuntu-latest
    # needs: check
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        run: rustup target add x86_64-unknown-linux-musl

      - name: Build json viewer
        run: cargo build --package json_viewer --release --target x86_64-unknown-linux-musl
      - name: Build json formatter
        run: cargo build --package json_formatter --release --target x86_64-unknown-linux-musl
      - name: Build executables installer
        run: cargo build --package executables_installer --release --target x86_64-unknown-linux-musl

      - name: Upload json viewer
        uses: actions/upload-artifact@v4.6.1
        with:
          name: json_viewer-linux-x86_64
          path: target/x86_64-unknown-linux-musl/release/json_viewer
      - name: Upload json formatter
        uses: actions/upload-artifact@v4.6.1
        with:
          name: json_formatter-linux-x86_64
          path: target/x86_64-unknown-linux-musl/release/json_formatter
      - name: Upload executables installer
        uses: actions/upload-artifact@v4.6.1
        with:
          name: executables_installer-linux-x86_64
          path: target/x86_64-unknown-linux-musl/release/executables_installer
